### ISSUE TITLE
adjusting dropdowns to be more semantic in the title

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/police_misconduct_pudding#12]
we could fix this by getting rid of "other" too, since "what happens when other officers receive complaints from other complainants" doesn't quite read sensibly.

the other option is something like:
 It would be more wordy, but you could reword to read: "What happens when officers (of all races/who identify as White/who identify as Black/who identify as Latino/of other races) receive complaints from complainants (of all races/who identify as White/who identify as Black/who identify as Latino/of other races) about incidents..."

**Comment by sdl60660** [comment]
<img width="377" alt="Screen Shot 2020-10-26 at 1 06 44 PM" src="https://user-images.githubusercontent.com/12772904/97204179-27787c80-178c-11eb-9306-08dc684d0339.png">

This is overall not too bad, but a few small things:

1. It seems like it's being pushed up a little vertically with the additional line
2. There's a lot of empty space on the right end of the select box when the first/last option is selected due to the difference in option text length
3. There's a sort of awkward amount of space on the right side of the first line on mobile, due to the length of the new select box.

First and third are mobile-only issues.

**Comment by matthewfdaniels** [comment]
what about `what happens when officers who are <white-identifying / of all races> receive complaints from people who are <white-identifying / of all races> ...`
